version: "3"
services:
  postgres:
    image: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/ro/Databases/postgres:/var/lib/postgresql/data
  cccm:
    depends_on:
      - postgres
    build:
      context: .
      args:
        - BINARY_PATH=./.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/cccm-exe/cccm-exe
    image: "cccm"
    container_name: cccm
    command: /opt/cccm/cccm-exe
    ports:
      - "8000:8000"
